# Generated by Django 4.1.4 on 2022-12-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_enrollment_membershipplan_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='PaymetStatus',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Salary',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
